version: "3.3"
services:
  executor:
    container_name: "executor"
    build:
      context: ./executor_new
    volumes:
      - ./executor_new:/app
    ports:
      - "5700:5700"
  client:
    container_name: "client"
    build:
      context: ./tryout-client
    stdin_open: true
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_BUILD=development
    volumes:
      - "./tryout-client:/usr/src/app"
